[package]
name = "plurigrid-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
yrs = "0.16.5"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
hyper = { version = "0.14", features = ["full"] }
